package com.example.model

/**
 * Domain representation of a mathematics problem generated by the engine.
 */
data class Problem(
    val id: String,
    val category: String,
    val topicId: String,
    val difficulty: String, // EASY, MEDIUM, HARD, EXPERT
    val question: String,
    val optionA: String,
    val optionB: String,
    val optionC: String,
    val optionD: String,
    val correctAnswer: String, // "A", "B", "C", or "D"
    val solution: String,
    val explanation: String,
    val formula: String? = null,
    val tags: String = "",
    val generator: String,
    val questionHash: String
)
